name: "GSEA"
description: "The Grinnell Space Exploration Agency"
url: "http://grinnellsea.github.io"

paginate: 10
paginate_path: "/blog/page:num/" 

defaults:
    -
        scope:
            path: ""
        values:
            layout: default
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: blog
            excerpt_separator: <!--END_EXCERPT-->

exclude: [vendor]
